[book]
title = "PersonalTest"
authors = ["ZxLili"]
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["mdbook-admonish.css", "./mdbook-admonish.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "{{#toc}}"
depth = 3

[preprocessor.mermaid]
command = "mdbook-mermaid"

